# Generated by Django 5.1.3 on 2024-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(default='', help_text='Введите задачу', max_length=400, verbose_name='Заголовок')),
                ('date_task', models.CharField()),
                ('time_task', models.CharField()),
            ],
        ),
    ]
