# Generated by Django 5.1.3 on 2024-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_model',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task_model',
            name='time_task',
        ),
        migrations.AlterField(
            model_name='task_model',
            name='date_task',
            field=models.DateTimeField(),
        ),
    ]
