# Generated by Django 5.1.3 on 2024-11-16 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_model_options_remove_task_model_time_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='time_task',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='task_model',
            name='date_task',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
