# Generated by Django 5.1.3 on 2024-11-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_model_time_task_alter_task_model_date_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_model',
            name='title_task',
            field=models.CharField(default='', help_text='Введите задачу', max_length=100, verbose_name='Заголовок'),
        ),
    ]
